architectury {
    common(["fabric", /*"neoforge"*/])
}

loom {
    accessWidenerPath = file("src/main/resources/hexplat.accesswidener")
}

shadowJar {
    zip64 = true
}

repositories {
    mavenCentral()
    mavenLocal()

    maven { url 'https://maven.blamejared.com' }

// At the time of modding this, this server died and gradle won't proceed to the fallback, so I commented it out
//    maven {
//        // location of the maven that hosts JEI files
//        name = "Progwml6 maven"
//        url = "https://dvs1.progwml6.com/files/maven/"
//    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }

    maven { url "https://maven.shedaniel.me/" }

    // EMI
    maven { url = "https://maven.terraformersmc.com/releases/" }
}

dependencies {
    // === MANDATORY DEPS ===
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    modCompileOnly "libs:paucal:$paucalVersion+$minecraftVersion-common"
    // i do not know why the xplat and mod jars are in different coordinates
    modCompileOnly "libs:Patchouli-xplat:1.21.4-$patchouliVersion-SNAPSHOT-dev"
    modCompileOnly "libs:inline-common:1.21.4-1.2.2"
    modRuntimeOnly "me.zeroeightsix:fiber:${project.fiber_version}"

    // === OPTIONAL DEPS ===
//    modCompileOnly "dev.emi:emi-xplat-intermediary:${emiVersion}:api"


    // === OTHER STUFF ===
    compileOnly "org.jetbrains:annotations:$jetbrainsAnnotationsVersion"
    testCompileOnly "org.jetbrains:annotations:$jetbrainsAnnotationsVersion"

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.6.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.6.1'
    testImplementation 'org.junit.platform:junit-platform-launcher:6.1.1'
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'

}

test {
    useJUnitPlatform()
}

processResources {
    def buildProps = project.properties.clone()

    filesMatching(['pack.mcmeta']) {
        expand buildProps
    }
}

// it wants a task by this name to exist for some reason
tasks.register('prepareWorkspace') {}

publishing {
    publications {
        hexCasting(MavenPublication) {
            groupId = "at.petra-k.$modID"
            artifactId = "$modID-$platform-$minecraftVersion"
            version = modVersion
            from components.java
        }
    }
    repositories {
        maven {
            url = System.getenv("LOCAL_REPO_URL")
        }
    }
}